Repository 2024INU-EPIC/Frontend, pull requests merged in 2025-05, with the labels that each got.

#120 feat: 내 정보 조회 API 연동
  package.json
  src/components/Header/Header.tsx
  src/pages/MainPage.tsx
  src/pages/SignPage.tsx
  src/stores/authStore.ts
  src/stores/userStore.ts
  yarn.lock
Labels: ✨ feat

#123 feat: 로그아웃 API 연동
  src/components/Header/Header.tsx
  src/pages/MainPage.tsx
  src/stores/userStore.ts
  vite.config.ts
Labels: ✨ feat

#125 fix:Part 4 modal 로직 수정
  src/pages/Part4Page.tsx
Labels: 🐛 fix

#127 design: 실전모의고사 안내페이지(direction) 퍼블리싱
  src/App.tsx
  src/pages/MainPage.tsx
  src/pages/MockDirection.styled.ts
  src/pages/MockDirectionPage.tsx
Labels: 🎨 design

#129 feat: 모의고사 시작 API 연동 및 Part1Page에 시범 적용
  src/pages/MainPage.tsx
  src/pages/MockDirection.styled.ts
  src/pages/MockDirectionPage.tsx
  src/pages/Part1Page.tsx
  src/stores/MockTestStore.ts
Labels: ✨ feat

#133 feat: 모의고사 완료 및 성적 반환 API 연동
  src/pages/Part5Page.tsx
Labels: ✨ feat

#136 feat: 모의고사 취소 API 연동
  src/hooks/useMockTestCancel.ts
  src/pages/Part1Page.tsx
  src/pages/Part2Page.tsx
  src/pages/Part3Page.tsx
  src/pages/Part4Page.tsx
  src/pages/Part5Page.tsx
Labels: ✨ feat

#138 design: 모의고사 결과용 페이지 퍼블리싱 및 모의고사 결과 응답 파싱
  src/App.tsx
  src/components/QuestionBody.tsx
  src/components/ReplyBody.tsx
  src/components/SituationBody.tsx
  src/components/StudyStatChart.tsx
  src/pages/MockExamResult.styled.ts
  src/pages/MockExamResultPage.tsx
  src/pages/MyPage.tsx
  src/pages/Part2Page.tsx
  src/pages/Part5Page.tsx
Labels: 🎨 design

#140 feat: responding 시작, 끝에 beep음 추가
  src/assets/audio/beep.mp3
  src/pages/Part1Page.tsx
  src/pages/Part2Page.tsx
  src/pages/Part3Page.tsx
  src/pages/Part4Page.tsx
  src/pages/Part5Page.tsx
Labels: ✨ feat

#145 feat: Part3Page의 situation 시간 제거
  src/pages/Part3Page.tsx
Labels: ✨ feat

#149 feat: PART3, 4, 5 TTS API 연동
  src/pages/Part3Page.tsx
  src/pages/Part4Page.tsx
  src/pages/Part5Page.tsx
  src/utils/tts.ts
Labels: ✨ feat

#152 feat: MyPage 유저 정보 세팅
  src/pages/MyPage.tsx
  src/stores/userStore.ts
Labels: ✨ feat

#155 fix: OnboardingPage PassageBody로 인한 오류 수정
  src/pages/MyPage.tsx
  src/pages/OnboardingPage.tsx
Labels: 🐛 fix

#159 design: 아이콘 수정 및 타이틀 수정
  index.html
  src/assets/img/epic.svg
  src/pages/Part1Page.tsx
  src/pages/Part2Page.tsx
  src/pages/Part3Page.tsx
  src/pages/Part4Page.tsx
  src/pages/Part5Page.tsx
Labels: 🎨 design
