Repository 2024INU-EPIC/Frontend, pull requests merged in 2025-03, with the labels that each got.

#34 design: part 3 페이지 퍼블리싱
  src/App.tsx
  src/components/MutipleReplyBox.tsx
  src/components/SituationBody.tsx
  src/pages/Part3Page.tsx
Labels: 🎨 design

#39 feat: 파트별 집중학습 '다음 문제 풀기'버튼 및 전환 기능 구현
  src/App.tsx
  src/assets/img/part2_2.png
  src/assets/img/part2_3.png
  src/assets/img/part2_4.png
  src/components/ImageBody.tsx
  src/pages/Part1Page.tsx
  src/pages/Part2Page.tsx
  src/pages/PartSelectPage.tsx
Labels: ✨ feat

#46 fix: part1 자동 재생 오류 및 문제 카운트 변수 수정, 준비, 응답 시간 수정
  src/pages/Part1Page.tsx
Labels: ✨ feat

#51 design: part3 direction 추가 및 파트별 집중학습 버튼 추가
  src/components/ImageBody.tsx
  src/components/SituationBody.tsx
  src/pages/Part2Page.tsx
  src/pages/Part3Page.tsx
Labels: 🎨 design

#54 design: 파트 4페이지 direction 추가 및 음성 적용
  src/pages/Part4Page.tsx
Labels: 🎨 design

#57 design: part5 direction 추가 및 파트별 집중학습 버튼 추가
  src/components/QuestionBody.tsx
  src/pages/Part5Page.tsx
Labels: 🎨 design

#60 fix: part4 direction 음성 조기종료 문제 해결
  src/pages/Part4Page.tsx
Labels: 🐛 fix

#64 feat:part1 파트별집중학습 버튼 추가 및 responding 로직 수정
  src/components/PassageBody.tsx
  src/pages/Part1Page.tsx
Labels: ✨ feat

#66 refactor:파트페이지 direction 시간 관리를 TIME_SETTINGS에서 설정하도록 변경
  src/pages/Part1Page.tsx
  src/pages/Part2Page.tsx
  src/pages/Part3Page.tsx
  src/pages/Part4Page.tsx
  src/pages/Part5Page.tsx
Labels: 🔨 refactor

#68 feat: part1 upload-audio Mocking Api 구현
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#70 feat: part1 문제 불러오기 Mocking Api 구현
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
  src/pages/PartSelectPage.tsx
Labels: ✨ feat

#73 feat: part1 문제 불러오기 방식 변경
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
  src/pages/PartSelectPage.tsx
Labels: ✨ feat

#80 feat: part1 upload-audio api 응답 수정
  src/App.tsx
  src/components/PassageBody.tsx
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
Labels: ✨ feat

#82 feat: part5 문제 불러오기 API 연동(Mock)
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
  src/pages/Part5Page.tsx
Labels: ✨ feat

#84 feat: part5 upload-audio API 연동(Mock)
  src/components/ReplyBody.tsx
  src/mocks/handlers.ts
  src/pages/Part1Page.tsx
  src/pages/Part5Page.tsx
Labels: ✨ feat

#90 Part3 문제불러오기(Mock)
  src/components/SituationBody.tsx
  src/mocks/handlers.ts
  src/pages/Part3Page.tsx
Labels: ✨ feat
